export default [
  {
    classes: ["col-12", "col-md-6", "text-left", "py-2"],
    label: "Adres",
    simpleRules: ["required"],
    complexRules: [],
    id: "accountSettingsStreet",
    key: "address_line_1",
    value: "",
  },
  {
    classes: ["col-12", "col-md-6", "text-left", "py-2"],
    label: "Miasto",
    simpleRules: ["required"],
    complexRules: [],
    id: "accountSettingsCity",
    key: "city",
    value: "",
  },
  {
    classes: ["col-12", "col-md-6", "text-left", "py-2"],
    label: "Kod pocztowy",
    simpleRules: ["required"],
    complexRules: [],
    id: "accountSettingsZipCode",
    key: "zip",
    value: "",
  },
  {
    classes: ["col-12", "col-md-6", "text-left", "py-2"],
    label: "Kraj",
    simpleRules: ["required"],
    complexRules: [],
    id: "accountSettingsCountry",
    key: "country",
    type: "select",
    value: "PL",
  },
];
