export default {
  serverError: `Błąd serwera przepraszamy...`,
  invalidLoginData: `Niepoprawne dane logowania!`,
  loginSuccess: `Pomyślnie zalogowano!`,
  registerSuccess: `Pomyślnie zarejestrowano! Sprawdź swoją skrzynkę mailową '{email}' oraz aktywuj konto!`,
  registerHurtSuccess: `Rejestracja przebiegła pomyślnie, po zweryfikowaniu danych firmy zostaniesz powiadomiony o pełnej aktywacji konta`,
  userDataEditSuccess: 'Pomyślnie edytowano dane użytkownika!',
  createAddressSuccess: 'Pomyślnie utworzono nowy adres!',
  updateAddressSuccess: 'Pomyślnie edytowano adres!',
  deleteAddressSuccess: 'Pomyślnie usunięto adres!',
  deleteAccountSuccess: 'Pomyślnie usunięto konto!',
  logoutSuccess: 'Pomyślnie wylogowano!',
  cartError: 'Przepraszamy, nie udało się załadować koszyka...',
  favouritesError:
    'Przepraszamy, nie udało się załadować ulubionych produktów...',
  userAddressesError:
    'Przepraszamy, nie udało się załadować adresów użytkownika...',
  deliveriesError: 'Przepraszamy, nie udało się załadować dostępnych dostaw...',
  paymentsError:
    'Przepraszamy, nie udało się załadować dostępnych metod płatności...',
  nonChoosedSizeError: 'Proszę wybrać rozmiar!',
  cartAddSuccess: 'Pomyślnie dodano produkt do koszyka!',
  cartEditSuccess: 'Pomyślnie edytowano koszyk!',
  cartDeleteSuccess: 'Pomyślnie usunięto produkt z koszyka!',
  rodoRequired: 'Proszę zaakceptować obowiązkowe rodo!',
  addToFavouritesSuccess: 'Pomyślnie dodano do ulubionych!',
  removeFromFavouritesSuccess: 'Pomyślnie usunięto z ulubionych!',
  cartUserDataNoAddress: 'Proszę wybrać adres wysyłki!',
  cartUserDataNoOtherAddress: 'Proszę wybrać drugi adres wysyłki!',
  cartUserDataSameOtherAddressError: 'Adresy muszą się różnić!',
  cartShippingPaymentNonChoosedDelivery: 'Proszę wybrać metodę dostawy!',
  cartShippingPaymentNonChoosedPayment: 'Proszę wybrać metodę płatności!',
  cartShippingPaymentNonChoosedParcelLocker: 'Proszę wybrać paczkomat!',
  cartSummaryRegulations: 'Proszę zatwierdzić regulamin sklepu!',
  createOrderSuccess: 'Pomyślnie utworzono zamówienie!',
  deliveryPricesError: 'Przepraszamy, nie udało załadować się cen dostaw...',
};
